import axios from 'axios';

/**
 * SIERRA BLU TELEGRAM ALERT HUB
 * Purpose: Instant escalation for VIP leads and high-propensity matches.
 */
export class TelegramAlertService {
  private static TOKEN = process.env.TELEGRAM_BOT_TOKEN;
  private static CHAT_ID = process.env.TELEGRAM_CHAT_ID;

  /**
   * Sends a tactical alert to the Telegram group.
   */
  static async sendVipMatchAlert(data: {
    leadName: string;
    propertyTitle: string;
    matchScore: number;
    budget: string;
    proposalUrl: string;
    roi: string;
  }): Promise<boolean> {
    if (!this.TOKEN || !this.CHAT_ID) {
      console.warn('Telegram Alert Service: Missing credentials.');
      return false;
    }

    const emoji = data.matchScore > 95 ? '💎' : '🔥';
    const message = `
${emoji} *HIGH-PRIORITY MATCH ALERT* ${emoji}
────────────────────────
👤 *Client:* ${data.leadName}
🏢 *Asset:* ${data.propertyTitle}
💹 *Score:* ${data.matchScore}%
💰 *Budget:* ${data.budget}
📈 *Est. ROI:* ${data.roi}

📍 [View Concierge Proposal](${data.proposalUrl})
────────────────────────
_Generated by Sierra Blu Matchmaker Agent Stage 7_
    `;

    try {
      await axios.post(`https://api.telegram.org/bot${this.TOKEN}/sendMessage`, {
        chat_id: this.CHAT_ID,
        text: message,
        parse_mode: 'Markdown',
        disable_web_page_preview: false
      });
      return true;
    } catch (error) {
      console.error('Telegram Alert Hub Failure:', error);
      return false;
    }
  }

  /**
   * Sends a system health or data event alert.
   */
  static async sendSystemAlert(event: string, details: string): Promise<boolean> {
    const message = `🛠 *SIERRA SYSTEM EVENT:* ${event}\n\n${details}`;
    try {
      await axios.post(`https://api.telegram.org/bot${this.TOKEN}/sendMessage`, {
        chat_id: this.CHAT_ID,
        text: message,
        parse_mode: 'Markdown'
      });
      return true;
    } catch (error) {
      return false;
    }
  }
}
